NielsSchmidtWebsite/NS-Web-v2/Models/EmailFormModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NS_Web_v2.Models
{
    public class EmailFormModel
    {
        [Required, Display(Name = "Your name")]
        public string FromName { get; set; }

        [Required, Display(Name = "Your email"), EmailAddress]
        public string FromEmail { get; set; }

        [Required, Display(Name = "Your type of interest")]
        public string Type { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

NielsSchmidtWebsite/NS-Web-v2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using NS_Web_v2.Models;

namespace NS_Web_v2.Controllers
{
    public class HomeController : Controller
    {
        public RedirectResult Index()
        {
            return Redirect("/Home/Introduction");
        }

        public ActionResult Introduction()
        {
            if (GetLanguage() == "DA")
                return View("Index_DA");

            return View("Index_EN");
        }

        public ActionResult Skills()
        {
            if (GetLanguage() == "DA")
                return View("Skills_DA");

            return View("Skills_EN");
        }

        public ActionResult Portfolio()
        {
            if (GetLanguage() == "DA")
                return View("Portfolio_DA");

            return View("Portfolio_EN");
        }

        public ActionResult Education()
        {
            if (GetLanguage() == "DA")
                return View("Education_DA");

            return View("Education_EN");
        }

        public ActionResult Work()
        {
            if (GetLanguage() == "DA")
                return View("Work_DA");

            return View("Work_EN");
        }

        public ActionResult ContactSent()
        {
            GetLanguage();
            return View();
        }

        public ActionResult ContactNotSent()
        {
            GetLanguage();
            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            if (GetLanguage() == "DA")
                return View("Contact_DA");

            return View("Contact_EN");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailFormModel model)
        {
            if (ModelState.IsValid)
            {
                var body = "<h3>You've got mail!</h3>" + "<p>"
                            + "<b>From:</b> " + model.FromName + "<br>"
                            + "<b>Email:</b> " + model.FromEmail + "<br>"
                            + "<b>Type:</b> " + model.Type.ToUpper() + "<br>"
                            + "<b>Language:</b> " + GetLanguage() + "</p>"
                            + "<p><b>Message:</b></p>" + model.Message;

                var message = new MailMessage();
                message.To.Add(new MailAddress(System.Configuration.ConfigurationManager.AppSettings.Get("email_address_to")));
                message.From = new MailAddress(System.Configuration.ConfigurationManager.AppSettings.Get("email_address_from"));
                message.Subject = "A '" + model.Type.ToUpper() + "' inquiry from " + model.FromName;
                message.Body = string.Format(body, model.FromName, model.FromEmail, model.Message);
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    smtp.UseDefaultCredentials = false;
                    var credential = new NetworkCredential
                    {
                        UserName = System.Configuration.ConfigurationManager.AppSettings.Get("email_username"),
                        Password = System.Configuration.ConfigurationManager.AppSettings.Get("email_password"),
                    };
                    smtp.Credentials = credential;
                    smtp.Host = System.Configuration.ConfigurationManager.AppSettings.Get("email_smtp");
                    smtp.Port = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings.Get("email_smtp_port"));
                    smtp.EnableSsl = Convert.ToBoolean(System.Configuration.ConfigurationManager.AppSettings.Get("email_smtp_ssl"));
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    await smtp.SendMailAsync(message);
                    return View("ContactSent");
                }
            }

            // If error - return ContactPage with model error messages.
            if (GetLanguage() == "DA")
                return View("Contact_DA", model);

            return View("Contact_EN", model);
        }

        public void ChangeLanguage(string language)
        {
            if (language == "DA")
            {
                HttpCookie cookie = new HttpCookie("language");
                cookie.Value = "DA";
                HttpContext.Response.Cookies.Remove("language");
                HttpContext.Response.SetCookie(cookie);
                Session["language"] = "DA";
            }
            else
            {
                HttpCookie cookie = new HttpCookie("language");
                cookie.Value = "EN";
                HttpContext.Response.Cookies.Remove("language");
                HttpContext.Response.SetCookie(cookie);
                Session["language"] = "EN";
            }
        }

        private string GetLanguage()
        {
            if (HttpContext.Request.Cookies["language"] != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("language");
                Session["language"] = cookie.Value;
                return cookie.Value;
            }
            else
            {
                string lang = GetBrowserLanguage();
                ChangeLanguage(lang);
                return lang;
            }
        }

        private string GetBrowserLanguage()
        {
            try
            {
                CultureInfo cult = CultureInfo.CreateSpecificCulture(Request.UserLanguages[0]);
                if (cult.Name == "da-DK")
                {
                    return "DA";
                }
                else
                {
                    return "EN";
                }
            }
            catch (Exception)
            {
                return "EN";
            }
        }
    }
}

NielsSchmidtWebsite/NS-Web-v2/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NS_Web_v2.Controllers
{
    public class PortfolioController : Controller
    {
        // GET: Portfolio
        public ActionResult Web()
        {
            if (GetLanguage() == "DA")
                return PartialView("_Web_DA");

            return PartialView("_Web_EN");
        }

        public ActionResult Wpf()
        {
            if (GetLanguage() == "DA")
                return PartialView("_Wpf_DA");

            return PartialView("_Wpf_EN");
        }

        public ActionResult Nuget()
        {
            if (GetLanguage() == "DA")
                return PartialView("_Nuget_DA");

            return PartialView("_Nuget_EN");
        }

        public ActionResult Winforms()
        {
            if (GetLanguage() == "DA")
                return PartialView("_Winforms_DA");

            return PartialView("_Winforms_EN");
        }

        private string GetLanguage()
        {

            if (HttpContext.Request.Cookies["language"] != null)
            {
                HttpCookie cookie = HttpContext.Request.Cookies.Get("language");
                Session["language"] = cookie.Value;
                return cookie.Value;
            }
            else
            {
                return "EN";
            }
        }
    }
}

NielsSchmidtWebsite/NS-Web-v2/Views/Home/ContactNotSent.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

@if (Session["language"].ToString() == "DA")
{
    ViewBag.Title = "Besked ikke sendt";
    <div class="well page-top-header">Beskeden blev IKKE sendt :-(</div>
}
else
{
    ViewBag.Title = "Message not Sent";
    <div class="well page-top-header">Message was NOT sent :-(</div>
}

<img src="https://i.giphy.com/g79am6uuZJKSc.gif" />
<br />
<br />

@if (Session["language"].ToString() == "DA")
{
    <p>
        Årh nej.. noget gik galt!<br/>
        Venligst prøv igen eller gå tilbage til forsiden.
    </p>
    <br/>
    <a class="btn btn-success" href="@Url.Action("Contact", "Home")">Prøv igen</a>
    <a class="btn btn-warning" href="@Url.Action("Index", "Home")">Tilbage til forsiden</a>
}
else
{
    <p>
        Oh snap.. something went wrong!<br />
        Please try again or return to the front page.
    </p>
    <br/>
    <a class="btn btn-success" href="@Url.Action("Contact", "Home")">Try again</a>
    <a class="btn btn-warning" href="@Url.Action("Index", "Home")">Back to the front page</a>
}

NielsSchmidtWebsite/NS-Web-v2/Views/Home/ContactSent.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["language"].ToString() == "DA")
{
    ViewBag.Title = "Besked sendt";
    <div class="well page-top-header">Besked sendt!</div>
}
else
{
    ViewBag.Title = "Message Sent";
    <div class="well page-top-header">Message sent!</div>
}

<img src="https://i.giphy.com/OBfYOx5gWfI9W.gif" />
<br />
<br />

@if (Session["language"].ToString() == "DA")
{
    <p>
        Tusind tak fordi du tog dig tid til at kontakte mig.<br />
        Jeg venter spændt på at modtage den og svare dig tilbage hurtigst muligt :-)
    </p>
    <br />
    <a class="btn btn-success" href="@Url.Action("Index", "Home")">Tilbage til siden</a>
}
else
{
    <p>
        Thank you so much for taking the time to contact me.<br />
        I am eagerly awaiting your message and will reply you as soon as possible. :-)
    </p>
    <br />
    <a class="btn btn-success" href="@Url.Action("Index", "Home")">Back to the site</a>
}

NielsSchmidtWebsite/NS-Web-v2/Views/Home/Contact_DA.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="well page-top-header">Kontakt</div>

@model NS_Web_v2.Models.EmailFormModel
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-sm-7 col-md-7">
            <h4>Venligst udfyld felterne for at komme i kontakt med mig.</h4>
            <hr />
        </div>
        <div class="hidden-xs">
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Dit navn</div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.FromName)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Din email</div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.FromEmail)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Type af interesse</div>
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Type, new SelectList(new List<Object>
                {
                    new {value = "personal", text = "Personlig"},
                    new {value = "business", text = "Forretning"},
                    new {value = "hiring", text = "Jeg vil ansætte dig!"},
                    new {value = "other", text = "Andet"},
                }, "value", "text", "personal"))
                <div style="color: red;">@Html.ValidationMessageFor(m => m.Type)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Besked</div>
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.Message)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="sendBtn" type="submit" class="btn btn-info" onclick="SendPress();" value="Send" />
            </div>
        </div>
    }
</div>

<script>
    function SendPress() {
        $("#sendBtn").val("Please wait...");
        $("#sendBtn").attr("class", "btn btn-warning disabled");
    }
</script>

NielsSchmidtWebsite/NS-Web-v2/Views/Home/Contact_EN.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="well page-top-header">Contact</div>

@model NS_Web_v2.Models.EmailFormModel
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="col-sm-7 col-md-7">
            <h4>Please fill out the form to get in touch with me.</h4>
            <hr />
        </div>
        <div class="hidden-xs">
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Your name</div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.FromName)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Your email</div>
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.FromEmail)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Your type of interest</div>
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Type, new SelectList(new List<Object>
                {
                    new {value = "personal", text = "Personal"},
                    new {value = "business", text = "Business"},
                    new {value = "hiring", text = "I want to hire you!"},
                    new {value = "other", text = "Other"},
                }, "value", "text", "personal"))
                <div style="color: red;">@Html.ValidationMessageFor(m => m.Type)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-2 control-label">Message</div>
            <div class="col-md-10">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                <div style="color: red;">@Html.ValidationMessageFor(m => m.Message)</div>
            </div>
        </div>
        <div class="hidden-xs hidden-sm">
            <br />
            <br />
            <br />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="sendBtn" type="submit" class="btn btn-info" onclick="SendPress();" value="Send" />
            </div>
        </div>
    }
</div>

<script>
    function SendPress() {
        $("#sendBtn").val("Please wait...");
        $("#sendBtn").attr("class", "btn btn-warning disabled");
    }
</script>

NielsSchmidtWebsite/NS-Web-v2/Views/Home/Education_DA.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Uddannelse";
}

<div class="well page-top-header">Uddannelse</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Erhvervs Akademi</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Uddannelse</th>
                    <th>År</th>
                    <th>Beskrivelse</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Datamatiker</td>
                    <td>2014-2017</td>
                    <td>Jeg tager datamatiker på Erhvervs Akademi Aarhus.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Skole</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Niveau</th>
                    <th>Beskrivelse</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>Folkeskole</td>
                <td>1988-2000</td>
                <td>Jeg har afsluttet 12. klasse.</td>
            </tr>
                <tr>
                    <td>HF</td>
                    <td>2009-2013</td>
                    <td>Afsluttet min gymnasiale eksamen på VUC Aarhus.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Andre typer skole eller studier</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>År</th>
                    <th>Beskrivelse</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>IT Højskole</td>
                    <td>2000</td>
                    <td>Jeg havde et 6 mdr. ophold på en IT højskole med speciale i netværk.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

NielsSchmidtWebsite/NS-Web-v2/Views/Home/Education_EN.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Education";
}

<div class="well page-top-header">Education</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Business Academy</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Major</th>
                    <th>Years</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Computer Science</td>
                    <td>2014-2017</td>
                    <td>I am getting my Computer Science degree at Business Academy Aarhus.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">School</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Type</th>
                <th>Years</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>High School</td>
                <td>1988-2000</td>
                <td>I have finished 12th grade.</td>
            </tr>
                <tr>
                    <td>College</td>
                    <td>2009-2013</td>
                    <td>Finished my college degree at VUC Aarhus.</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Other types of school or study</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Type</th>
                <th>Years</th>
                <th>Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>IT School</td>
                <td>2000</td>
                <td>I had a 6 months stay at an IT school with major in networking.</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

NielsSchmidtWebsite/NS-Web-v2/Views/Portfolio/_Nuget_DA.cshtml
<h2>Nuget Galleri Projekter</h2>
<hr/>

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">WPF Startup Manager</h3>
    </div>
    <div class="panel-body">
        <div class="pull-right label label-success">Udgivet</div>
        <p>Et lille bibliotek på NuGet galleriet til at starte en WPF applikation sammmen med windows.</p>

        <h3>For hvem</h3>
        <p>Alle der har brug for det, jeg har selv haft brug for det mange gange, og besluttede mig for at lave og udgive en pakke der var nem at bruge.</p>

        <h3>Tekniske detaljer</h3>
        <p>Lavet som et C# Class Library.</p>
        <p>Det tilføjer programmet til windows registrerings databasen der håndtere start af applikationer.</p>

        <h3>Preview</h3>
        <p>Ikke tilgængelig</p>

        <h3>Screenshots</h3>
        <p>Ikke tilgængelig</p>

        <h3>Yderligere info</h3>
        <a class="btn btn-info" href="https://github.com/itniels/WPF-Startup-Manager">Github</a>
        <a class="btn btn-info" href="https://www.nuget.org/packages/NovaKittySoftware.wpf.StartupManager/">Nuget Gallery</a>
    </div>
</div>

NielsSchmidtWebsite/NS-Web-v2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - NielsSchmidt.dk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/unobjq")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/cookie-concent")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="hidden-sm">
                    @Html.ActionLink("Niels Schmidt", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="hidden-xs hidden-md hidden-lg">
                    @Html.ActionLink("NS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["language"].ToString() == "DA")
                    {
                        <li>@Html.ActionLink("Introduktion", "Index", "Home")</li>
                        <li>@Html.ActionLink("Færdigheder", "Skills", "Home")</li>
                        <li>@Html.ActionLink("Portefølje", "Portfolio", "Home")</li>
                        <li>@Html.ActionLink("Uddannelse", "Education", "Home")</li>
                        <li>@Html.ActionLink("Arbejde", "Work", "Home")</li>
                        <li>@Html.ActionLink("Kontakt Mig", "Contact", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Introduction", "Index", "Home")</li>
                        <li>@Html.ActionLink("Skills", "Skills", "Home")</li>
                        <li>@Html.ActionLink("Portfolio", "Portfolio", "Home")</li>
                        <li>@Html.ActionLink("Education", "Education", "Home")</li>
                        <li>@Html.ActionLink("Work", "Work", "Home")</li>
                        <li>@Html.ActionLink("Contact Me", "Contact", "Home")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden-xs hidden-md hidden-lg"><a href="#" onclick="ChangeLanguage('EN');"><img src="/Content/Images/Site/flag_round_usa.png" height="25" /></a></li>
                    <li class="hidden-xs hidden-md hidden-lg"><a href="#" onclick="ChangeLanguage('DA');"><img src="/Content/Images/Site/flag_round_denmark.png" height="25" /></a></li>

                    <li class="hidden-sm"><a href="#" onclick="ChangeLanguage('EN');"><img src="/Content/Images/Site/flag_round_usa.png" height="25" /> English</a></li>
                    <li class="hidden-sm"><a href="#" onclick="ChangeLanguage('DA');"><img src="/Content/Images/Site/flag_round_denmark.png" height="25" /> Dansk</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="hidden-sm hidden-md hidden-lg">
            <div align="center" class="sidebar">
                <div class="row">
                    <div class="col-xs-7 name-text">
                        Niels Schmidt<br />
                        @if (Session["language"].ToString() == "DA")
                        {
                            <div class="name-text-sub">//Software Udvikler//</div>
                        }
                        else
                        {
                            <div class="name-text-sub">//Software Developer//</div>
                        }

                    </div>
                    <div class="col-xs-3">
                        <img src="/Content/Images/Site/Niels_Small_Round.png" class="form-control-static" height="140" />
                    </div>
                </div>
                @if (Session["language"].ToString() == "DA")
                {
                    <h3 id="lang_sidebar_FindMeOn">Find mig på</h3>
                }
                else
                {
                    <h3 id="lang_sidebar_FindMeOn">Find me on</h3>
                }

                <a href="https://github.com/itniels" target="_blank">Github</a> |
                <a href="https://www.linkedin.com/in/niels-schmidt-75054b44" target="_blank">LinkedIn</a> |
                <a href="https://itniels.dk" target="_blank">ITNiels - Tech Blog</a> |
                <a href="https://novakittysoft.dk" target="_blank">NovaKitty Software</a>
            </div>
            <br />
        </div>

        <div class="row">
            <div align="left" class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                <div class="body-content">
                    @RenderBody()
                </div>
            </div>
            <div align="center" class="hidden-xs sidebar col-sm-4 col-md-4 hidden-lg">
                <div class="name-text">
                    Niels Schmidt<br />
                    @if (Session["language"].ToString() == "DA")
                    {
                        <div class="name-text-sub">//Software Udvikler//</div>
                    }
                    else
                    {
                        <div class="name-text-sub">//Software Developer//</div>
                    }
                </div>

                <img src="/Content/Images/Site/Niels_Small_Round.png" class="form-control-static" height="200" />
                @if (Session["language"].ToString() == "DA")
            {
                    <h3 id="lang_sidebar_FindMeOn">Find mig på</h3>
                }
                else
                {
                    <h3 id="lang_sidebar_FindMeOn">Find me on</h3>
                }
                <a href="https://github.com/itniels" target="_blank">Github</a> <br />
                <a href="https://www.linkedin.com/in/niels-schmidt-75054b44" target="_blank">LinkedIn</a> <br />
                <a href="https://itniels.dk" target="_blank">ITNiels - Tech Blog</a> <br />
                <a href="https://novakittysoft.dk" target="_blank">NovaKitty Software</a>
            </div>
            <div align="center" class="hidden-xs sidebar hidden-sm hidden-md col-lg-4">
                <div class="name-text">
                    Niels Schmidt<br />
                    @if (Session["language"].ToString() == "DA")
                    {
                        <div class="name-text-sub">//Software Udvikler//</div>
                    }
                    else
                    {
                        <div class="name-text-sub">//Software Developer//</div>
                    }
                </div>
                <img src="/Content/Images/Site/Niels_Small_Round.png" class="form-control-static" height="300" />
                @if (Session["language"].ToString() == "DA")
            {
                    <h3 id="lang_sidebar_FindMeOn">Find mig på</h3>
                }
                else
                {
                    <h3 id="lang_sidebar_FindMeOn">Find me on</h3>
                }
                <a href="https://github.com/itniels" target="_blank">Github</a> <br />
                <a href="https://www.linkedin.com/in/niels-schmidt-75054b44" target="_blank">LinkedIn</a> <br />
                <a href="https://itniels.dk" target="_blank">ITNiels - Tech Blog</a> <br />
                <a href="https://novakittysoft.dk" target="_blank">NovaKitty Software</a>
            </div>
        </div>
    </div>

    @if (Session["language"].ToString() == "DA")
    {
        <div class="footer navbar-fixed-bottom navbar-inverse">
            <div id="lang_footer_long" align="center" class="text-footer hidden-xs">Designet, skrevet og programeret af Niels Schmidt - &copy; Copyright 2016.</div>
            <div id="lang_footer_short" align="center" class="text-footer hidden-sm hidden-md hidden-lg">Lavet af Niels Schmidt - &copy; Copyright 2016.</div>
        </div>
    }
    else
    {
        <div class="footer navbar-fixed-bottom navbar-inverse">
            <div id="lang_footer_long" align="center" class="text-footer hidden-xs">Created, written and programmed by Niels Schmidt - &copy; Copyright 2016.</div>
            <div id="lang_footer_short" align="center" class="text-footer hidden-sm hidden-md hidden-lg">Created by Niels Schmidt - &copy; Copyright 2016.</div>
        </div>
    }


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/tracking")

</body>
</html>

<script>
    // Changes the site language and refreshes the current page.
    function ChangeLanguage(lang) {
        $.ajax({
            type: "POST",
            url: "ChangeLanguage",
            data: { language: lang }
        }).done(function () {
            location.reload();
        });
    }
</script>